spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/petpi
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
    show-sql: false

server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9090

openai:
  api-key: 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
  model: gpt-3.5-turbo

file:
  dir: /src/main/resources/pet-image/

logging:
  level:
    org:
      springframework:
        web:
          servlet: info